<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!DOCTYPE bix
        [
        <!ELEMENT bix (package+)>
        <!ELEMENT package (id?, name?)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        ]
        >

<!-- PUBLIC "http://iubio.bio.indiana.edu/grid/runner/docs//bix.dtd" -->
<!-- FIXME for bix dialog parser - any "choice" field should install runSwitch
	 from parlist options.  Now have to put each parlist.par runswitch into
	 action line -->
<bix>

    <package age="">
        <id>111</id>
        <name hasEntityReference="true">  汤姆克鲁兹-&amp;c&#244;t&#233;<![CDATA[ &amp;c&#244;t&#233;  ]]></name>
    </package>
    <package  sex="male">
        <id>222</id>
        <name hasEntityReference="false">weager</name>
    </package>
    <package>
        <id>333</id>
        <name />
    </package>

</bix><!-- this is comment2 -->
